// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClW8tI4eqnno4S0rgKKna9YIdDItMxu3Y',
    appId: '1:866299929331:web:c0f4f40bd0555a4b80cd86',
    messagingSenderId: '866299929331',
    projectId: 'weatherapp-b8d3e',
    authDomain: 'weatherapp-b8d3e.firebaseapp.com',
    storageBucket: 'weatherapp-b8d3e.appspot.com',
    measurementId: 'G-PZCYJ5J224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYOqMdz08t8qiEufAxOmx-0kkGxW-0wf0',
    appId: '1:866299929331:android:cae2c78a7ebf490c80cd86',
    messagingSenderId: '866299929331',
    projectId: 'weatherapp-b8d3e',
    storageBucket: 'weatherapp-b8d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXDaMP76p3GNPPBk3qeOPo_I9vI-H-Gs',
    appId: '1:866299929331:ios:1e27f01bb827018080cd86',
    messagingSenderId: '866299929331',
    projectId: 'weatherapp-b8d3e',
    storageBucket: 'weatherapp-b8d3e.appspot.com',
    iosClientId: '866299929331-9908dvq61n9ttsjg7r6an0h0a7tssnir.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherShow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFXDaMP76p3GNPPBk3qeOPo_I9vI-H-Gs',
    appId: '1:866299929331:ios:65ec10a5805f341b80cd86',
    messagingSenderId: '866299929331',
    projectId: 'weatherapp-b8d3e',
    storageBucket: 'weatherapp-b8d3e.appspot.com',
    iosClientId: '866299929331-adud5dms698lpbsvqb734nr4k35r40k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherShow.RunnerTests',
  );
}
